# Generated by Django 4.2.23 on 2025-10-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_rating_points_profile_tier_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
