# Generated by Django 4.2.23 on 2025-10-16 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_change_total_hours_to_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='friend_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.friendrequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('match_invite', 'Match Invitation'), ('match_reminder', 'Match Reminder'), ('match_accepted', 'Match Accepted'), ('match_cancelled', 'Match Cancelled'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('achievement', 'Achievement Unlocked')], max_length=20),
        ),
    ]
