# Generated by Django 4.2.23 on 2025-10-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_friend_request_to_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='reservation_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
