# Generated by Django 4.2.23 on 2025-10-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_club_reservation_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
