# Generated by Django 4.2.10 on 2026-06-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_club_manager_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='right_handed',
            field=models.BooleanField(default=True),
        ),
    ]
