# Generated by Django 4.2.10 on 2026-07-08 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_profile_right_handed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('match_invite', 'Invitation au match'), ('match_reminder', 'Rappel de match'), ('match_accepted', 'Match accepté'), ('match_cancelled', 'Match annulé'), ('friend_request', 'Demande d\'ami'), ('friend_accepted', 'Demande d\'ami acceptée'), ('achievement', 'Succès déverrouillé'), ('booking_confirmed', 'Réservation confirmée')], max_length=20),
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
