# Generated by Django 4.2.10 on 2026-08-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_notification_type_emailverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='category',
            field=models.CharField(choices=[('general', 'Général'), ('tips', 'Conseils & Astuces'), ('tournaments', 'Tournois'), ('equipment', 'Équipement'), ('clubs', 'Clubs'), ('looking_for_players', 'Recherche de joueurs')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='court',
            name='court_type',
            field=models.CharField(choices=[('glass', 'Terrain vitré'), ('indoor', 'Terrain intérieur'), ('outdoor', 'Terrain extérieur'), ('concrete', 'Terrain en béton'), ('premium', 'Terrain premium'), ('standard', 'Terrain standard')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Refusé')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='app.court'),
        ),
        migrations.AlterField(
            model_name='match',
            name='evaluation_type',
            field=models.CharField(choices=[('new', 'Nouveau (1-8)'), ('old', 'Ancien (1-10)')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('casual', 'Amical'), ('competitive', 'Compétitif'), ('tournament', 'Tournoi'), ('training', 'Entraînement')], default='casual', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('full', 'Complet'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchparticipant',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchparticipant',
            name='status',
            field=models.CharField(choices=[('empty', 'Vide'), ('pending', 'En attente'), ('confirmed', 'Confirmé'), ('declined', 'Refusé'), ('cancelled', 'Annulé')], default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='evaluation_type',
            field=models.CharField(choices=[('new', 'Échelle 8 Niveaux (FFT)'), ('old', 'Échelle 10 Niveaux')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Gestionnaire'), ('player', 'Joueur')], default='player', max_length=10),
        ),
    ]
